### PR TITLE
Multiple fixes and enhancements, doc and code

### PR DESCRIPTION
**Pull request by sdetweil**
Two most important changes
Doc , an alternative config approach
Adding ability to have different page display times
Adding package.json for improved visibility
In the new 3rd party modules list
Add support for my MMM-Config modile which creates a form for config. No more editing js

### CODE REVIEW

**Comment by sdetweil** [comment]
ok, let me think about how to do that. 
 its been a couple years worth

I'm the forum and discord moderator
i do the MagicMirror install and upgrade scripts 
and have a few modules myself. 

the big file size is the customized MMM-Config form template for use w my MMM-Config module that creates a form for  config
https://github.com/sdetweil/MMM-Config

**Comment by sdetweil** [comment]
and Kristian has developed a new 3rd party module list which requires a good package.json for all  the metadata

**Comment by edward-shen** [comment]
Well, if it's too much work I can try to find some time to review it. It's just going to take some time. 

Smaller PRs make it easier for me to incrementally merge. Larger ones need a solid chunk of time in my experience to give decent consideration to all the changes.

Let me know which you'd like.

**Comment by sdetweil** [comment]
again ill look at it

they were all small at the time

you appeared gone, so i made updates to my fork to help the users

**Comment by sdetweil** [comment]
see the other PRs.. 74-78, numbered in order as the later include the earlier

**Comment by sdetweil** [comment]
and fyi, you can checkout a commit as a branch, which is what I did here from the git log

I left out the noise of renaming the module to MMM-Pages, and all the trouble that caused.. so reverted.. 
its in one of the prs, but noise

**Comment by sdetweil** [comment]
closing for individual prs

**Pull request closed without merging**
